name: Docker

on: 
  push

jobs:
  run-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:13.5.0-alphine3.10
    steps:
      - name: log node
        run: |
         node -v
         cat /etc/os-release