name: Shell Commands

on: [push]

jobs: 
  run-shell-command: 
    runs-on: ubuntu-lastest
    steps:
      - name: echo a string
      run: echo "Hello world"
      - name: multiline script
      run: |
        node -v
        npm - v